language: node_js
node_js:
  - "stable"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

before_install:
  - npm up -g npm
  - npm --version

git:
  depth: 10
