language: node_js
node_js:
  - "stable"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

before_install:
  - npm up -g npm
  - npm --version

after_success:
  - ./node_modules/.bin/coveralls --verbose < test/coverage/lcov.info

git:
  depth: 10
